"""Generate opscale.ltx - a table of Operatinf Profit multipliers
"""

import datetime
from string import Template

import aswath

plate = r"""
%autogenerated by opscal.py - do not manually edit
\begin{table}[H]

\caption{Scale of Operating profit for dividend cover by return on capital. Assumes $ c_t = h_1 = $ct $ , $ g_t = $gt $, $ \tau = $taxr $. These values are as at $dstamp, and were generates by the program \texttt{opscale.py}.}

\begin{tabular}{ r | r r r r r r}
\hline
 & 5 & 10 & 15 & 20 & 25 & 30 \\ \hline
$vals
\hline
\end{tabular}
%\begin{tablenotes}
%This table is complied with the assumptions 
%\end{tablenotes}
\label{tbl:opscale}
\end{table}
"""

def main():
    global plate
    tem = Template(plate)
    vals = ""
    for w in range(10, 51, 2):
        w *= 0.1
        def cell(r): return "{0:7.3f}".format(aswath.grow2b(1, w, r*0.01, 0))
        nums = ["{0:.1f}".format(w)]
        for r in range(5, 31, 5): nums.append(cell(r))            
        row = " & ".join(nums)
        vals += row + "  \\\\\n"

    dst = datetime.datetime.now().strftime("%d %B %Y")
    d = dict(vals=vals, ct = aswath.ct_default, gt=aswath.gt_default,
             taxr = aswath.taxr_default, dstamp = dst)
    text = tem.safe_substitute(d)
    open("../manual/opscale.ltx", "w").write(text)
    #print(text)
    #print(plate)

            
if __name__ == "__main__":
    main()
